baseurl = "https://phreaknik.github.io/fullhack-blog/"
languageCode = "en-us"
title = "blog.johnboyd.io"
paginate = "10" # Number of posts per page
theme = "Mainroad"
copyright = "&copy; 2017, John Boyd IV.<br> All rights reserved."
canonifyurls = true
googleAnalytics = "Your Google Analytics tracking ID"
disqus = "fullhackblog"
publishDir = "docs"

[Author]
    author = "John Boyd IV"
    bio = "John Boyd's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/headshot.png"

[Params]
    subtitle = "Solder, code and GPIOs."
    description = " John Doe's Personal blog about everything" # Description of your site
    opengraph = true
    readmore = true # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true
    postSections = ["post"]

[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    recent_articles_num = 10 # Set the number of articles in the "Recent articles" widget
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget
    tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)
    social = true # Enable "Social" widget
    social_linkedin = "john-boyd-iv"
    social_github = "phreaknik"
    social_email = "johnboydiv@gmail.com"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    weight = 2
    url = "/post/"
  [[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"